name: avarizia-database
services:
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    env_file:
      - .env
    ports:
      - "6346:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    env_file:
      - .env
    ports:
      - "6483:80"

volumes:
  db_data:
    driver: local
